n = int(input('Digite um número: '))
print('-'*12)
print('{} X 0 = {:2}'.format(n, n * 0))
print('{} X 1 = {:2}'.format(n, n * 1))
print('{} X 2 = {:2}'.format(n, n * 2))
print('{} X 3 = {:2}'.format(n, n * 3))
print('{} X 4 = {:2}'.format(n, n * 4))
print('{} X 5 = {:2}'.format(n, n * 5))
print('{} X 6 = {:2}'.format(n, n * 6))
print('{} X 7 = {:2}'.format(n, n * 7))
print('{} X 8 = {:2}'.format(n, n * 8))
print('{} X 9 = {:2}'.format(n, n * 9))
print('{} x 10 = {:2}'.format(n, n * 10))
print('-'*12)